### ISSUE TITLE
[Bug]: Bed Bugs

### ISSUE THREAD

**Issue by NorthWestTrees** [MCreator-Examples/Tale-of-Biomes#40]
### Issue information

> Also another bug, when placing the bed it can delete a full block up one and you can't place the bed in a 1 by two hole facing south the not been able to place and deleting the block as both facing south
> 
> - BabyMaxy2006

> They there nice work but your beds are not working I know you only have a option to mimic the sleep it's not a real laydown sleep but it don't even let you sleep I think your maths might be incorrect.
> 
> - BabyMaxy2006

### Steps to reproduce

As described above

### Build information

ToB: r0.2.0-Indev
Forge: 1.20.1

**Comment by northwesttreesgaming** [comment]
Fixed in R-0.4.0-Indev
