### ISSUE TITLE
[Feature]: Greenhouse block

### ISSUE THREAD

**Issue by Manyaarvadiya** [MCreator-Examples/Tale-of-Biomes#63]
### Feature information

need to make a oxygen distributer block for my mod so please bro

**Comment by northwesttreesgaming** [comment]
I had plans to make a greenhouse for crops, though it's for plants it could be adapted for an oxygen system. However, I will need to figure this out when the time comes because at the moment I am not sure how to do it and I need to finish up the rice crop mechanics before I can start working on this which has been on hold until other systems are in place.

But I will work towards this in the future for sure.
I have marked this as to do so I can keep track of the progress.

**Comment by Manyaarvadiya** [comment]
Any ideas or logic on how this could work. As this is the only thing left in my mod. And mod jam deadline is near and still can't figure it out

There is code for it in ad astra GitHub but I don't know how to read Java or any stuff so like please

**Comment by northwesttreesgaming** [comment]
I have not brainstormed any ideas on how to do this yet nor have I done it so I can't really say what would work or not.
With that said I have a few tutorials grass spreading mechanics and even other blocks that replace things over time.
This could be used to spread invisible blocks that when the or entity is in them give them NBT for what ever oxygen level you have.

You would also want to make an air-tight block and set a rough distance which any six sides of the location the air would spread to is in reach of an air-tight block, this way natural shelters like caves would not provide a place for it to spread to as this could cause major lag in post generation conditions.

The last thing you would need is some kind of source I guess the source would generate air blocks.
As far as leaking mechanics I have no idea how this would work. Maybe you could test if there were gaps but this goes into coding. I am no programmer so I have no clue how this would be done but as an airtight room, this would at least give you the foundations for it. 3D objects may also require custom versions depending on how the player can walk in them just keep this in mind as in some cases non-air pockets could cause the air blocks to go through. You may want to try making them skip 1 block, in this case, this way it has a chance to jump obstructions but other than that I have no idea how to do it.

Greenhouse it would be less important to make a sealed room all I would need to do is test if the blocks are next to it and the plants are indoors. This could technically be applied the same way but this would in some cases court as outdoors if the player or entity was on the other side of the blocks with one block above. Just something to keep in mind I guess.

In cases like this, I wish we had a way to make custom air blocks like cave air and such but we don't at the moment.

**Comment by Manyaarvadiya** [comment]
Well we can make air blocks. Just set it's texture to a transparent texture which you can make by erasing an existing texture. Then set it's bounding box to 0 and make it replaceable which is a tick box. And wallah it's a air block

**Comment by northwesttreesgaming** [comment]
Yea I see your point, though 3D models still render the spaces as air, doing it this way would not fill those spaces with your block you would need custom blocks for that or do it through conditions to make it count which is what I was trying to say.

Water acts much the same way as air in that regard as it works with 3D models, you can still breathe in them even when standing next to them if you place a fence in your gas it should be able to keep the gas while still providing the 3D model. Sadly though placing a fence would just add a regular fence with actual air.

So a bit different mechanics than actual air or water.
